### 1. Summarize for us the goal of this project and how machine learning is useful in trying to accomplish it. As part of your answer, give some background on the dataset and how it can be used to answer the project question. Were there any outliers in the data when you got it, and how did you handle those?  [relevant rubric items: “data exploration”, “outlier investigation”]
The goal of this project is to find and tune a machine learning algorithm that can predict whether or not a given Enron employee is a person of interest (POI) with precision and recall of at least 0.3 given the dataset provided which is basically a list of enron employees with some data about their income (salary, stocks, etc) and their email data. 
In the data exploration phase I removed 3 outliers which were: 
* the TOTAL line which doesn't add any new information to the dataset because - as the name suggests - is just the sum of the columns values.
* the LOCKHART EUGENE E line which is empty
* the THE TRAVEL AGENCY IN THE PARK line which is clearly not an Enron employee

### 2. What features did you end up using in your POI identifier, and what selection process did you use to pick them? Did you have to do any scaling? Why or why not? As part of the assignment, you should attempt to engineer your own feature that does not come ready-made in the dataset -- explain what feature you tried to make, and the rationale behind it. (You do not necessarily have to use it in the final analysis, only engineer and test it.) In your feature selection step, if you used an algorithm like a decision tree, please also give the feature importance of the features that you use, and if you used an automated feature selection function like SelectKBest, please report the feature scores and reasons for your choice of parameter values.  [relevant rubric items: “create new features”, “properly scale features”, “intelligently select feature”]
My decision was to use all features available but email\_address (because it's just strings that doesn't bring any value to the model) and total_payments and total_stock_value (because those are only total columns that sum up other features). This decision was made because I thought that using all features available and then using PCA to reduce dimensionality was the best move to be made here.
While tunning the algorithm I've tried different values as the number of components of the PCA trying to find the one that would give me the best accuracy and that has been done using GridSearchCV.
I also added 2 more features for each employee named total_emails_related_to_poi and emails_percentage_related_to_poi. The total_emails_related_to_poi feature is the total emails sent or recieved by that employee to/from a POI while the emails_percentage_related_to_poi is the percentage of the emails of that employee that are from/to a POI.
I did this based on the assumption that the more one employee communicates with POIs more likely he/she is a POI.
I did use feature scaling in my pipeline based on the observation that different columns have much different scaling. Some columns can reach tens of millions while other columns doesn't get close to that.

### 3. What algorithm did you end up using? What other one(s) did you try? How did model performance differ between algorithms?  [relevant rubric item: “pick an algorithm”]
I''ve tried the following algorythms: NearestNeighbors, DecisionTreeClassifier, RandomForestClassifier, ExtraTreesClassifier and GaussianNB.
The second best one has been the DecisionTreeClassifier which has given me the numbers below:

Accuracy: 0.85873 Precision: 0.45475  Recall: 0.29900 F1: 0.36078 F2: 0.32099 Total predictions: 15000
True positives:  598  False positives:  717 False negatives: 1402 True negatives: 12283

But the one that has given me the best precision and recall numbers has been the GaussianNB:
Accuracy: 0.83733 Precision: 0.38730  Recall: 0.37800 F1: 0.38259 F2: 0.37982
Total predictions: 15000  True positives:  756  False positives: 1196 False negatives: 1244 True negatives: 11804

Even though I could get better Accuracy with other algorithms I could not tune any other algorithm that would give me both Precision and Recall > 0.3 as required.


### 4. What does it mean to tune the parameters of an algorithm, and what can happen if you don’t do this well?  How did you tune the parameters of your particular algorithm? (Some algorithms do not have parameters that you need to tune -- if this is the case for the one you picked, identify and briefly explain how you would have done it for the model that was not your final choice or a different model that does utilize parameter tuning, e.g. a decision tree classifier).  [relevant rubric item: “tune the algorithm”]
Tuning the parameters of an algorithm is an art but you can leverage the use of tools such as GridSearchCV to help you became a good artist. The idea of the tuning process is to find values of the set of parameters of a given algorithm that will give you the best result and by result here I mean the object that you choose, in our case precision and recall.
Another way of tuning is to pick the right pre-process steps to use in the pipeline. Be it a scaler, imputer, pca, etc. 
In my final pipeline I''ve ended up using, I''ve used a scaler, PCA, a KBest selector besides the GaussianNB algorithm, of course.
I'll paste below some params I've used together with GridSearchCV in order to tune some of the algorithms I've tried:
##### DecisionTreeClassifier
param_grid = dict(pca__n_components = [4, 5, 6, 'mle', None], 
                  kbest__k = [4, 5, 6],    
                  clf__criterion = ['gini', 'entropy'],
                  clf__splitter = ['best', 'random'],
                  clf__min_samples_split = [12, 14, 16, 18], 
                  clf__max_features = ['auto', 'sqrt', 'log2', None],
                  clf__max_depth = [3, 4, 5],
                  clf__presort = [True, False],
                  clf__class_weight = [None, "balanced"]) 

##### NearestNeighbors
param_grid = dict(pca__n_components = [5, 10, 'mle', None], 
                  kbest__k = [1, 5, 10],    
                  clf__n_neighbors = [5, 10, 15, 20],
                  clf__algorithm : ['auto', 'ball_tree', 'kd_tree', 'brute'], 
                  clf__leaf_size = [20, 30, 40],
                  clf__max_depth = [5, 10],
                  clf__metric = ['cityblock', 'cosine', 'euclidean', 'l1', 'l2', 'manhattan', 'minkowski'],
                  clf__n_jobs = [-1]) 

##### RandomForestClassifier
param_grid = dict(
                  pca__n_components = [5, 10, 'mle', None], 
                  kbest__k = [1, 5, 10],
                  clf__n_estimators = [5, 10, 15],
                  clf__criterion = ['gini', 'entropy'],
                  clf__min_samples_split = [10, 20, 30], 
                  clf__max_features = ['auto', 'sqrt', 'log2', None],
                  clf__max_depth = [5, 10],
                  clf__max_depth = [10],
                  clf__class_weight = [None, "balanced", "balanced_subsample"],
                  clf__warm_start = [False],
                  clf__n_jobs = [-1]) 

None of those has given me better results for precision and recall than this one:
param_grid = dict(
                  imputer__strategy = ["mean", "median"],
                  scaler__with_mean = [True, False],
                  scaler__with_std = [True, False],
                  scaler__copy = [True, False],
                  pca__n_components = [5, 10, 15, 'mle', None]
                  ) 

### 5. What is validation, and what’s a classic mistake you can make if you do it wrong? How did you validate your analysis?  [relevant rubric item: “validation strategy”]
Validation is the method used to validate if the chosen algorythm will perform well with real data and in order to assure this we split our data into train and test data sets so we can fit our algorithm using the training dataset and test its efficiency against the test dataset. A classic mistake here is to poorly split these datasets so that you end up with only instances of one label in the training dataset and only instances of the other label in the test dataset. Another issue that might happen when we use the same dataset for training and testing is overfitting.
I''ve used the StratifiedShuffleSplit to crossvalidate my model for a number of reasons but mainly because it''s easy to set up and it assures me that it''s using randomization to split the dataset and it''s the same strategy used in the test.py class used to validate my code.

### 6. Give at least 2 evaluation metrics and your average performance for each of them.  Explain an interpretation of your metrics that says something human-understandable about your algorithm’s performance. [relevant rubric item: “usage of evaluation metrics”]
The main evaluation metrics used were precision and recall. The average performance for each of them was 0.38730 for precision  and 0.37800 for recall.
My interpretation of these 2 metrics:
Recall is the probability of the algorithm to identify an employee as a POI provided that the employee is a POI. 
Precision is the probability that the algorithm is right when it says that an employee is a POI.